### find cast by movie id
GET http://localhost:8000/api/cast-management/findCastByMovieId?movieId=61c984ec29bca9fad6f2032e
Content-Type: application/json
Accept: application/json

### add new Cast
POST http://localhost:8000/api/cast-management/addNewCast
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTczNGQ2NjA1ZGZiMTc1YWJjMmQwMiIsImlhdCI6MTY0MDA3Nzg4OSwiZXhwIjozNjAwMTY0MDA3Nzg4OX0.xNAdxVXQToCSMCshMXJR3nYOb09lvT7eC5z_5OeGSGE

{
  "castName":"Brie Larson1",
  "castAvatar":"",
  "status":1,
  "movieId": "61927578bbc196473ef8dc9b"
}


### update Cast
PUT http://localhost:8000/api/cast-management/updateCast/61c1e3d70763b3de3ae52b4f
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTczNGQ2NjA1ZGZiMTc1YWJjMmQwMiIsImlhdCI6MTY0MDA3Nzg4OSwiZXhwIjozNjAwMTY0MDA3Nzg4OX0.xNAdxVXQToCSMCshMXJR3nYOb09lvT7eC5z_5OeGSGE

{
  "castName":"MacIOS",
  "castAvatar":"a",
  "status":1,
  "movieId":[
    "61bf89a429bca9fad6019fc7",
    "61bf89a429bca9fad6019fc5",
    "61bf89a429bca9fad6019fc6"
  ],
}

### delete Cast
DELETE http://localhost:8000/api/cast-management/deleteCast/61bf3a0b9854b8872c0e88d4
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTczNGQ2NjA1ZGZiMTc1YWJjMmQwMiIsImlhdCI6MTY0MDA3Nzg4OSwiZXhwIjozNjAwMTY0MDA3Nzg4OX0.xNAdxVXQToCSMCshMXJR3nYOb09lvT7eC5z_5OeGSGE
