# GET http://localhost:8000 HTTP/1.1

### FIND ALL GENREBOOK
GET http://localhost:8000/api/genrebook-management/getGenreBook

### ADD GENREBOOK
POST http://localhost:8000/api/genrebook-management/addGenreBook
Authorization: 
Content-Type: application/json
Accept: application/json

{
  "name": "Khoa Học"
}

### DELETE GENREBOOK BY ID
DELETE  http://localhost:8000/api/genrebook-management/deleteGenreBook/622aeb5452377538463592ed HTTP/1.1
Authorization: 
Content-Type: application/json
Accept: application/json

### UPDATE GENREBOOK BY ID
PUT http://localhost:8000/api/genrebook-management/updateGenreBook?id=622aeb6a52377538463592f3 HTTP/1.1
Authorization: 
Content-Type: application/json
Accept: application/json

{
  "name" : "Trinh Thám"
}