### add comment
POST http://localhost:8000/api/comment-management/addComment/
Content-Type: application/json
Accept: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZDJlYzhhOTcxNTUyN2ExZjYzNzkwMiIsImlhdCI6MTY0MTMwNzI4OSwiZXhwIjoxNjQxMzEwODg5fQ.OLhrjmkgySkkGD8VM5mcCUll7JzO6h6Sb0GqCy9PXr0

{
  
  "idMovie":"61bf89a429bca9fad6019fc6",
  "content":"phim hay 22",
  "rating":2,
  "status":1,
  "likes":[],
  "disLikes":[],
  "createAt":"",
  "updateAt":"",
  "deleteAt":""
}
### update Comment
PUT http://localhost:8000/api/comment-management/updateComment/61cacc5c19296bc1917f1aed
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTczNGQ2NjA1ZGZiMTc1YWJjMmQwMiIsImlhdCI6MTY0MDY5NTIyMywiZXhwIjoxNjQwNjk4ODIzfQ.fcb3vvuN6f0SpMVpXOQr7kAPhos-eQFVLnCwHQU0h50

{
  "idUser":"61a734d6605dfb175abc2d02",
  "idMovie":"61bf89a429bca9fad6019fc6",
  "content":"phim hay quá trời",
  "rating":2,
  "status":1,
  "likes":[],
  "disLikes":[],
  "createAt":"2021-12-23T17:00:00.000+00:00",
  "updateAt":"2021-12-23T17:00:00.000+00:00",
  "deleteAt":"2021-12-23T17:00:00.000+00:00"
}

### delete Comment
DELETE http://localhost:8000/api/comment-management/deleteComment/61cafde495418eb7eb6e651b
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTczNGQ2NjA1ZGZiMTc1YWJjMmQwMiIsImlhdCI6MTY0MDc0MjU2MSwiZXhwIjoxNjQwNzQ2MTYxfQ.Z_6kgMnJyR0q2oLYg8IsfF6RrA2QCUAaoAU176i1vUo

{
  "idUser":"61a734d6605dfb175abc2d02"
}
### Like
PUT http://localhost:8000/api/comment-management/likeAndUnlikeComment/61cc2833abecb24f71c0e4fd
Content-Type: application/json
Accept: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZDJlYzhhOTcxNTUyN2ExZjYzNzkwMiIsImlhdCI6MTY0MTU2ODA5MiwiZXhwIjoxNjQxNTcxNjkyfQ.hMjSHXc0-9JMvBgtaHEx27ETG-jhntIZdlEYIHdpa_g



### DisLike
PUT http://localhost:8000/api/comment-management/likeAndDislikeComment/61cafde495418eb7eb6e651b/dislike
Content-Type: application/json
Accept: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZDQ1NzdiN2NhZDYxZDgxMmQ0MTUzMyIsImlhdCI6MTY0MTU2NzEwMiwiZXhwIjoxNjQxNTcwNzAyfQ.IPxZpTzo5g835mxD4hOrg9bS1JSLXgXtURoFbLpKoQ0

{
  "disLikes":"61c97c1e4533fd7b082de81a"
}

### unlike
PUT http://localhost:8000/api/comment-management/likeAndDislikeComment/61cafde495418eb7eb6e651b/unlike
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTczNGQ2NjA1ZGZiMTc1YWJjMmQwMiIsImlhdCI6MTY0MDY5NTIyMywiZXhwIjoxNjQwNjk4ODIzfQ.fcb3vvuN6f0SpMVpXOQr7kAPhos-eQFVLnCwHQU0h50

{
  "likes":"61c97c1e4533fd7b082de81a"
}

### undislike
PUT http://localhost:8000/api/comment-management/likeAndDislikeComment/61cafde495418eb7eb6e651b/undislike
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTczNGQ2NjA1ZGZiMTc1YWJjMmQwMiIsImlhdCI6MTY0MDY5NTIyMywiZXhwIjoxNjQwNjk4ODIzfQ.fcb3vvuN6f0SpMVpXOQr7kAPhos-eQFVLnCwHQU0h50

{
  "disLikes":"61cb066b06d031ce587c4255"
}

### get all comment phân trang
GET http://localhost:8000/api/comment-management/getAllCommentSort?idMovie=61c984ec29bca9fad6f2033c&page=1
Content-Type: application/json
Accept: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxY2YxMWY3YzU5OTg3YWIwNmYyNDZlOCIsImlhdCI6MTY0MTIwMzcyMCwiZXhwIjoxNjQxMjA3MzIwfQ.LvypaLHas3u5qsTauIjRCcGENP9FRcYf0L9FifX9jTo

